### ISSUE TITLE
social icons

### ISSUE THREAD

**Issue by domi64** [GavickPro/Magazine-Free-Joomla-Template#1]
Hello

How can i change the social icons? i don't need an icon of pinterest but one for xing.com. Is that possible to do?

Domi64

**Comment by bkrztuk** [comment]
You mean social api icons at the bottom of article?

**Comment by domi64** [comment]
No. Position "social" with the icons of twitter, facebook, pinterest, google+... on the left side. You know where i mean?

**Comment by bkrztuk** [comment]
Yes, this is custom HTML module and to remove pinterest please just open module configuration and from code remove this line : 

```
<a class="gk-icon-pinterest" href="http://www.pinterest.com/robertgavick/"></a>
```

We've included this few icons into font but there are no additional icons which you can use with in template so the only way is to create your own icon, upload to template directory and add custom CSS code to display it properly.

**Comment by domi64** [comment]
can you tell me where exactly i could find this line? Which file do you mean?

Is it possible here: modules/mod_nice_social_bookmark/css

Thank you very much for your support/help!

**Comment by bkrztuk** [comment]
The file where all template custom changes should be added is _override.css_ which you will find in root/templates/gk_magazine/css directory. Please check our wiki articles about template customizations: 

→ [How to Add or Use Custom CSS in Template ? – GavickPro Documentation](http://www.gavick.com/documentation/joomla-templates/customizing-joomla-template/how-to-add-custom-css-to-joomla-template/)
→ [How to add & change Social Icons – GavickPro Documentation](http://www.gavick.com/documentation/general-questions/how-to-add-change-social-icons/)

**Comment by domi64** [comment]
thank you very much!!!! :-)

**Comment by aml987** [comment]
![capture](https://cloud.githubusercontent.com/assets/7550942/2959812/9271180e-dab6-11e3-9847-2d2271605d6d.GIF)
Can I add Youtube icon to social module?

**Comment by bkrztuk** [comment]
Sure, but we didn't prepared the icon so you need to create your own CSS, this may be helpful → [The easiest way to create multiple resolution-independent social icons - Joomla Templates, WordPress Themes - GavickPro](https://www.gavick.com/magazine/the-easiest-way-to-create-multiple-resolution-independent-social-icons.html)

**Comment by tsanwie** [comment]
the social link on my website is not working, can anyone assist me on how to edit the link. thanks
my site is http://www.sabana.com
