### ISSUE TITLE
Load compressed JavaScript and CSS with "async" attribute

### ISSUE THREAD

**Issue by jozsefke** [GavickPro/Magazine-Free-Joomla-Template#18]
I have enabled JavaScript and CSS compression in the template settings. I checked my site with Google PageSpeed, and it considers the compressed output files as render blocking resources. Is it possible to include an "async" attribute for the script tags in the head section?

**Comment by dziudek** [comment]
Hello,

Please try to use this extension: http://extensions.joomla.org/profile/extension/core-enhancements/performance/javascript-async-and-defer

**Comment by jozsefke** [comment]
Hello dziudek,

Thank you for your help! I have managed to load the script asynchronously, but this way, all the jQuery function breaks unfortunately. I get javascript jQuery not defined errors everywhere, because the jQuery isn't loaded first, the order of scripts are different.

Is there a solution for it?

**Comment by dziudek** [comment]
I afraid that only way is remove loading scripts from the code level and add it manually in the footer as HTML code - but it is a custom work beyond of our technical support
