### ISSUE TITLE
Module / Component positioning

### ISSUE THREAD

**Issue by PedroDK** [GavickPro/Magazine-Free-Joomla-Template#2]
Hi GavickPro on Github,
In the Magazine template's frontpage there's a large single featured article on top of a group of "Featured news".
How would it be possible to interchange those two positions, so that the "Featured news" - group was placed on top of the large single featured article?
Can that be done? 
I can't find any module or position for the "Mainbody/Component" position as displayed on the Module positions overview in the demo of the Magazine template.
Thank you for your time.
best regards
Pedro

**Comment by bkrztuk** [comment]
Please try to publish featured news module in mainbody_top position, this should change the order in this area.

**Comment by PedroDK** [comment]
Hi Bartłomiej Krztuk,

Thank you for your advice – it works very well.

In the Magazine template the Featured News module is the News Show Pro GK4 version.

I have downloaded the  https://www.gavick.com/free-joomla-modules/news-show-pro-gk5-free-joomla-module,124.html News Show Pro GK5 module.

Can I implement this module as a substitution for the GK4 version and use it much the same way?

I really like the slider-ish features of the GK5 version.

Thank you again.

Best regards

Pedro

Fra: Bartłomiej Krztuk [mailto:notifications@github.com] 
Sendt: 9. april 2014 18:45
Til: GavickPro/Magazine-Free-Joomla-Template
Cc: PedroDK
Emne: Re: [Magazine-Free-Joomla-Template] Module / Component positioning (#2)

Please try to publish featured news module in mainbody_top position, this should change the order in this area.

**Comment by bkrztuk** [comment]
Yes GK5 may be used as a GK4 substitute but probably due to fact that GK4 has custom styles included in template it will not work exactly like the GK4 version. All the hover effects are available in NSP GK4 only in this template, this means that even GK4 in standalone version (with other template) don't have this features.

**Comment by PedroDK** [comment]
Hi,

Thank you for your quick reply.

Couldn’t the hover styles be copied on to this GK5 version? It would require that I know my way around CSS, I guess… J

Thanks

Pedro

Fra: Bartłomiej Krztuk [mailto:notifications@github.com] 
Sendt: 10. april 2014 09:07
Til: GavickPro/Magazine-Free-Joomla-Template
Cc: PedroDK
Emne: Re: [Magazine-Free-Joomla-Template] Module / Component positioning (#2)

Yes GK5 may be used as a GK4 substitute but probably due to fact that GK4 has custom styles included in template it will not work exactly like the GK4 version. All the hover effects are available in NSP GK4 only in this template, this means that even GK4 in standalone version (with other template) don't have this features.

**Comment by PedroDK** [comment]
Hi Bartłomiej Krztuk,

I am having some trouble controlling what featured article should be the first in the component below the GK4 news module.

Where (or how) can I control this?

Thanks

Pedro

**Comment by PedroDK** [comment]
Hi again,
I hope you can help me out with another question concerning the way the Magazine template displays Catoegory views. In my version there's a very large and quite pixelated folder icon .png image, above the category view listing.

When I check with the demo's category view, (i.e. Ultrabooks) on GavickPro it's not there.

Please see the attached screendump.

Thanks

Pedro
![screendump-magazine-cat-view](https://cloud.githubusercontent.com/assets/2134372/2672889/2c261be6-c0ec-11e3-82ec-8f611261c866.jpg)

**Comment by bkrztuk** [comment]
Please try to create new issues with new problems because it will be much easier to manager status of this problems. In regard to your problem you need to disable K2 catalog mode, more details you will find here:
 → [Catalog Layout](http://getk2.org/community/English-K2-Community/161280-Catalog-Layout) or
→ [Remove large folder icon?](http://getk2.org/community/English-K2-Community/680-Remove-large-folder-icon)

 but this is K2 configuration issue not template problem.
