### ISSUE TITLE
Pagination number of pages

### ISSUE THREAD

**Issue by jozsefke** [GavickPro/Magazine-Free-Joomla-Template#23]
I have enabled the pagination on my website for blog layout using the Magazine template. It worked fine until I only had 6 pages of content, but now I have started page number 7, and the pagination looks like this:
![](http://i.imgur.com/aFyM1av.png)
How can I make it display more pages e.g the last few ones after the button with "..."?

**Comment by dziudek** [comment]
Hello,

Please change "7" in the following line: https://github.com/GavickPro/Magazine-Free-Joomla-Template/blob/master/gk_magazine/html/pagination.php#L14 to a higher value - if you want to have a lot of pagination buttons I suggest you a high number like 100, because in other case you will have to override this file many times.

**Comment by jozsefke** [comment]
Thank you for your help, Dziudek!

I wouldn't like to display all the pagination buttons, but only a few more on the first page where I have plenty of space left. It could display pages number 4 and 5 but only displays until 3. How can I make it display a little more on the first page?

**Comment by dziudek** [comment]
https://github.com/GavickPro/Magazine-Free-Joomla-Template/blob/master/gk_magazine/html/pagination.php#L24-L35 - in this fragment please try to change every "2" value to "3".

**Comment by jozsefke** [comment]
Thank you very much for your support. I had this idea too, but this way the pagination becomes too wide from page 4 and so on. Is it possible to display more buttons only on the first page (and maybe the last)?

**Comment by dziudek** [comment]
Sorry but it needs more complicated code changes which are beyond of our technical support.
