### ISSUE TITLE
can't make website work online without login 

### ISSUE THREAD

**Issue by kevinas** [GavickPro/Magazine-Free-Joomla-Template#7]
I have a strange problem.. I have been working on the website and  when I thought I was finished I put it online. At first the login still showed. I turned of the module login, it still showed. I even trashed the login it did not work. I took the url for the login away in the template manager. Now the login screen doesn't show on the online website, but the menu (path/adress/redirection) to the content doesn't work. When I turn on the login (offline or online) and I fill in the username and password I get in the website and then it works just fine. So what could be causing this problem?

I checked the database, turned the module of, even disabled the com_user to see if this would help (I only got a 404 error). So put this all back. I checked the user view access, everything is on public. I am pretty desperate at the moment, I just don't understand what is causing this. Just now I thought about your support, maybe I should have thought about that earlier, but normally I always try to solve things myself. I really hope you are willing to help me with this and can find the problem. The website is www.burenco.com then you see the problem with the menu's

So how do I get the website working normally without filling in a login? Is it because of the index.php maybe? 

Thank you in advance.

**Comment by bkrztuk** [comment]
It looks like problem with publishing modules if you see content which is inactive. Please make sure that cache is disabled and refresh your browser cache.

**Comment by kevinas** [comment]
cache was and is disabled, all content active and published. But your other tip did something good, the url thing.

**Comment by bkrztuk** [comment]
So the problem is resolved or not? If not, please check whether the same happen on Beez template.

**Comment by kevinas** [comment]
Hi bartlomiej,

I think it is resolved for the most part. There is only one thing that
doesn't load after a refresh, but i think that is because of the component
and not the template, so I asked at support for that component, have to
wait what he says about it. So for know O want to Thank you for your help,
appreciate it.

Grz.

Op maandag 2 juni 2014 heeft Bartłomiej Krztuk notifications@github.com
het volgende geschreven:

**Comment by bkrztuk** [comment]
Ok, please let us know when you get response - I'll keep this issue open.

**Comment by kevinas** [comment]
hi Bartomiej,

You can close the issue.. It was what you said... i turned of the cache,
but in the global options, not the template cache. The problem was the GK
cache was in conflict with the extension's cache. When I turned it off, it
works fine.

Thank you very much for your work.

2014-06-06 12:16 GMT+02:00 Bartłomiej Krztuk notifications@github.com:
